version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "password"
      MONGO_INITDB_DATABASE: "animal_db"
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  frontend:
    build: ./frontend/app
    environment:
      API_URL: "http://localhost:8000"
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    environment:
      MONGO_USERNAME: "root"
      MONGO_PASSWORD: "password"
      MONGO_DATABASE: "animal_db"
      MONGO_URL: "mongo"
    ports:
      - "8000:8000"
    depends_on:
      - mongo


